(document).ready(function(){
    $(document).on('click','#getLink',function(){
        $.ajax({
            url:'.',
            method:'POST',
            data:{
                calendar:$("option:selected").val()
            },
            success:function(data){
                $('#yourLink').html(data.link)
                console.log(data);
            },
            error:function(data){
                console.log(data);
            }
        });
    });
});