$(document).ready(function(){
    $(document).on('click','#getLink',function(){
        $.ajax({
            url:'../utilities/get_link.php',
            method:'POST',
            data:{
                calendar:$("option:selected").val()
            },
            success:function(data){
                $('#yourLink').html(data.link);
                console.log(data.link);
            },
            error:function(data){
                console.log(data.link);
            }
        });
    });
});